apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-aws-auth.fullname" . }}-permissions
  labels: {{- include "nats-aws-auth.labels" . | nindent 4 }}
data:
  nats-aws-auth.toml: {{ .Values.auth.config | toYaml | nindent 4 }}
